// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: article.proto

package server

import (
	"context"

	"inquora/application/article/rpc/internal/logic"
	"inquora/application/article/rpc/internal/svc"
	"inquora/application/article/rpc/pb"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) Publish(ctx context.Context, in *pb.PublishRequest) (*pb.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *ArticleServer) ArticleList(ctx context.Context, in *pb.ArticleListRequest) (*pb.ArticleListResponse, error) {
	l := logic.NewArticleListLogic(ctx, s.svcCtx)
	return l.ArticleList(in)
}

func (s *ArticleServer) ArticleDetail(ctx context.Context, in *pb.ArticleDetailRequest) (*pb.ArticleDetailResponse, error) {
	l := logic.NewArticleDetailLogic(ctx, s.svcCtx)
	return l.ArticleDetail(in)
}
