// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: like.proto

package server

import (
	"context"

	"inquora/application/like/rpc/internal/logic"
	"inquora/application/like/rpc/internal/svc"
	"inquora/application/like/rpc/pb"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) ThumbUp(ctx context.Context, in *pb.ThumbUpRequest) (*pb.ThumbUpResponse, error) {
	l := logic.NewThumbUpLogic(ctx, s.svcCtx)
	return l.ThumbUp(in)
}

func (s *LikeServer) IsThumbUp(ctx context.Context, in *pb.IsThumbUpRequest) (*pb.IsThumbUpResponse, error) {
	l := logic.NewIsThumbUpLogic(ctx, s.svcCtx)
	return l.IsThumbUp(in)
}
